### ISSUE TITLE
Failed at the nutch-web-api@1.0.0 start script 'coffee app.coffee'.

### ISSUE THREAD

**Issue by pranipat** [wei-m-teh/nutch-web-api#1]
AssertionError: handler (function) is required
  at process (/var/www/html/nutch-web-api/node_modules/restify/lib/server.js:65:24)
  at process (/var/www/html/nutch-web-api/node_modules/restify/lib/server.js:63:17)
  at argumentsToChain (/var/www/html/nutch-web-api/node_modules/restify/lib/server.js:73:13)
  at Server.(anonymous function) [as get](/var/www/html/nutch-web-api/node_modules/restify/lib/server.js:400:13)
  at addMethod (/var/www/html/nutch-web-api/node_modules/swagger-node-restify/Common/node/swagger.js:411:23)
  at /var/www/html/nutch-web-api/node_modules/swagger-node-restify/Common/node/swagger.js:436:5
  at Function.forOwn (/var/www/html/nutch-web-api/node_modules/lodash/dist/lodash.js:1301:15)
  at addHandlers (/var/www/html/nutch-web-api/node_modules/swagger-node-restify/Common/node/swagger.js:434:5)
  at Object.addGet (/var/www/html/nutch-web-api/node_modules/swagger-node-restify/Common/node/swagger.js:460:3)
  at Object.create (/var/www/html/nutch-web-api/docs/swagger.coffee:12:10)
  at Object.startServer (/var/www/html/nutch-web-api/server.coffee:19:10)
  at Domain.<anonymous> (/var/www/html/nutch-web-api/app.coffee:16:9)
  at Domain.run (domain.js:221:14)
  at Object.<anonymous> (/var/www/html/nutch-web-api/app.coffee:15:8)
  at Object.<anonymous> (/var/www/html/nutch-web-api/app.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.exports.run (/var/www/html/nutch-web-api/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/var/www/html/nutch-web-api/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/var/www/html/nutch-web-api/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/var/www/html/nutch-web-api/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/var/www/html/nutch-web-api/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Function.Module.runMain (module.js:575:10)
  at startup (node.js:160:18)
  at node.js:449:3

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! nutch-web-api@1.0.0 start: `coffee app.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nutch-web-api@1.0.0 start script 'coffee app.coffee'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nutch-web-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee app.coffee
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nutch-web-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nutch-web-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/nutch-web-api/npm-debug.log

**Comment by sjwoodard** [comment]
Same issue

**Comment by YJ14** [comment]
same here. Any update planned soon?
